[build]
builder = "NIXPACKS"

[deploy]
startCommand = "bun --filter './hono-api' start"
buildCommand = "bun --filter './hono-api' build"

[phases.install]
cmds = ["bun install --frozen-lockfile"]

[phases.build]
cmds = ["bun --filter './hono-api' build"]