import type { paths } from "@generated/weather-api/fetch-client"; // generated by openapi-typescript

import createClient from "openapi-fetch";

export const weatherClient = createClient<paths>({
	baseUrl: "https://api.weather.gov",
});
